### ISSUE TITLE
Can`t clone needs password

### ISSUE THREAD

**Issue by njovanoski** [kovin/bitcoin-simgrid#1]
Hi i cant clone the repository with the command in the description.
I did clone the repository using the link in the github provided about the repository but after running "cmake ." successfully the "make" command failed. 

Please help and thanks

**Comment by kovin** [comment]
Hi njovanoski

Sorry for the late reply. Did you run the command in the pre-requisites
section?
ie:

$ cd ~
$ sudo apt-get install doxygen libboost-all-dev cmake valgrind
python-networkx python-lxml git
$ git clone --branch v3_21 --depth 1
https://framagit.org/simgrid/simgrid.git simgrid
$ cd simgrid
simgrid$ cmake -DCMAKE_INSTALL_PREFIX=/opt/simgrid .
simgrid$ make simgrid
simgrid$ sudo make install


I just tried all the steps again without problem, but perhaps I have
another dependency that I forgot to list?

Please paste any error you get when running the "Preequisites"
commands and then the "Clone" commands

Cheers,

Kevin

**Comment by njovanoski** [comment]
Hi Kovin 
Thanks for your reply.
So the thing is i can do all of this but i can`t clone the repository for the bitcoin simgrid after using the command: 
git clone git@gitlab.licar.exp.dc.uba.ar:licar/bitcoin-simgrid.git
I get the following message so do i have to use password or how it goes .

Cloning into 'bitcoin-simgrid'...
git@gitlab.licar.exp.dc.uba.ar's password: 
Permission denied, please try again.

Thanks a lot for your help
